# -*- coding: utf-8 -*-
"""infosys coding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kGvPBDcVvu48k41nEuLWPddgBtEbRdac

ramu has n dishes
"""

t = int(input())

for tc in range(t):
  n = int(input())
  itemlist = list(map(int, input().split()))
  max_count = 0
  item_type = itemlist[0]

  for i in range(n):
    count = itemList.count(itemList[i])
    if count > max_count:
      max_count = count
      item_type = item_list[i]

  print(item_type)

"""N homeless people"""

N = int(input())
people = []
house = []

for i in range(N):
  people.append(int(input()))
for i in range(N):
  house.append(int(input()))
count=0
for i in range(N):
  for j in range(N):
    if (people[i] < house[j]):
      count+=1
      house[j]=-1
      break
print(N-count)

"""Bhojon is the restaurant company"""

n = int(input())
m = 0
mxPos= 0
v = []
x = int(input())
v_input = input().split()
for i in range(n):
  v.append(int(v_input[i]))
  v[i] = (v[i]-1)//x
  if v[i] >= m:
    m = v[i]
    mxpos = i
print(mxPos+1)

"""3 piles of stones"""

t = int(input())

for _ in range(t):
    a, b, c, x, y = map(int, input().split())

    if (a + b + c) != (x + y) or y < min(a, min(b, c)) or x < min(a, min(b, c)):
        print("NO")
    else:
        print("YES")

"""parallel coloumbus"""

import math
n = int(input())-1
m = int(input())-1
x = int(input())-1
y = int(input())-1
ans = math.factorial(n+m)
ans = ans//(math.factorial(n))
ans = ans//(math.factorial(m))
ans1 = math.factorial(x+y)
ans = ans//(math.factorial(x))
ans = ans//(math.factorial(y))
x1 = n-x
y1 = m-y
ans2 = math.factorial(x1+y1)
ans2 = ans2//(math.factorial(x1))
ans2 = ans2//(math.factorial(y1))
print(ans-(ans1*ans2))